/*
 * rcc_registers.h
 *
 * Defines macros for STM32F407VG RCC peripheral registers.
 */

#ifndef RCC_REGISTERS_H
#define RCC_REGISTERS_H

/* RCC peripheral base address from STM32F407VG reference manual, Table 1 */
#define RCC_BASE_ADDR   0x40023800

/* RCC register offsets from STM32F407VG reference manual Table 33 */
#define RCC_CR_OFFEST   		0x00
#define RCC_PLLCFGR_OFFEST 		0x04
#define RCC_CFGR_OFFSET 		0x08
#define RCC_CIR_OFFSET  		0x0C
#define RCC_AHB1RSTR_OFFSET 	0x10
#define RCC_AHB2RSTR_OFFSET 	0x14
#define RCC_AHB3RSTR_OFFSET 	0x18
#define RCC_APB1RSTR_OFFSET 	0x20
#define RCC_APB2RSTR_OFFSET 	0x24
#define RCC_AHB1ENR_OFFSET 		0x30
#define RCC_AHB2ENR_OFFSET 		0x34
#define RCC_AHB3ENR_OFFSET 		0x38
#define RCC_APB1ENR_OFFSET 		0x40
#define RCC_APB2ENR_OFFSET 		0x44
#define RCC_AHB1LPENR_OFFSET	0x50
#define RCC_AHB2LPENR_OFFSET	0x54
#define RCC_AHB3LPENR_OFFSET	0x58
#define RCC_APB1LPENR_OFFSET	0x60
#define RCC_APB2LPENR_OFFSET	0x64
#define RCC_BDCR_OFFSET			0x70
#define RCC_CSR_OFFSET			0x74
#define RCC_SSCGR_OFFSET		0x80
#define RCC_PLLI2SCFGR_OFFSET	0x84
#define RCC_PLLSAICFGR_OFFSET	0x88
#define RCC_DCKCFGR_OFFSET		0x8C

/* RCC register address definitions */
#define RCC_CR          (RCC_BASE_ADDR + RCC_CR_OFFEST)
#define RCC_PLLCFGR     (RCC_BASE_ADDR + RCC_PLLCFGR_OFFEST)
#define RCC_CFGR        (RCC_BASE_ADDR + RCC_CFGR_OFFSET)
#define RCC_CIR         (RCC_BASE_ADDR + RCC_CIR_OFFSET)
#define RCC_AHB1RSTR    (RCC_BASE_ADDR + RCC_AHB1RSTR_OFFSET)
#define RCC_AHB2RSTR    (RCC_BASE_ADDR + RCC_AHB2RSTR_OFFSET)
#define RCC_AHB3RSTR    (RCC_BASE_ADDR + RCC_AHB3RSTR_OFFSET)
#define RCC_APB1RSTR    (RCC_BASE_ADDR + RCC_APB1RSTR_OFFSET)
#define RCC_APB2RSTR    (RCC_BASE_ADDR + RCC_APB2RSTR_OFFSET)
#define RCC_AHB1ENR     (RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)
#define RCC_AHB2ENR     (RCC_BASE_ADDR + RCC_AHB2ENR_OFFSET)
#define RCC_AHB3ENR     (RCC_BASE_ADDR + RCC_AHB3ENR_OFFSET)
#define RCC_APB1ENR     (RCC_BASE_ADDR + RCC_APB1ENR_OFFSET)
#define RCC_APB2ENR     (RCC_BASE_ADDR + RCC_APB2ENR_OFFSET)
#define RCC_AHB1LPENR   (RCC_BASE_ADDR + RCC_AHB1LPENR_OFFSET)
#define RCC_AHB2LPENR   (RCC_BASE_ADDR + RCC_AHB2LPENR_OFFSET)
#define RCC_AHB3LPENR   (RCC_BASE_ADDR + RCC_AHB3LPENR_OFFSET)
#define RCC_APB1LPENR   (RCC_BASE_ADDR + RCC_APB1LPENR_OFFSET)
#define RCC_APB2LPENR   (RCC_BASE_ADDR + RCC_APB2LPENR_OFFSET)
#define RCC_BDCR        (RCC_BASE_ADDR + RCC_BDCR_OFFSET)
#define RCC_CSR         (RCC_BASE_ADDR + RCC_CSR_OFFSET)
#define RCC_SSCGR       (RCC_BASE_ADDR + RCC_SSCGR_OFFSET)
#define RCC_PLLI2SCFGR  (RCC_BASE_ADDR + RCC_PLLI2SCFGR_OFFSET)
#define RCC_PLLSAICFGR  (RCC_BASE_ADDR + RCC_PLLSAICFGR_OFFSET)
#define RCC_DCKCFGR     (RCC_BASE_ADDR + RCC_DCKCFGR_OFFSET)

#endif // RCC_REGISTERS_H
