/*
 * rtc_registers.h
 *
 * Defines macros for STM32F407VG RTC peripheral registers.
 */

#ifndef RTC_REGISTERS_H
#define RTC_REGISTERS_H

/* RTC peripheral base address from STM32F407VG reference manual, Table 1 */
#define RTC_BASE_ADDR   0x40002800

/* RTC register offsets from STM32F407VG reference manual Table 121 */
#define RTC_TR_OFFEST   	0x00
#define RTC_DR_OFFEST 		0x04
#define RTC_CR_OFFSET 		0x08
#define RTC_ISR_OFFSET  	0x0C
#define RTC_PRER_OFFSET 	0x10
#define RTC_WUTR_OFFSET 	0x14
#define RTC_CALIBR_OFFSET 	0x18
#define RTC_ALRMAR_OFFSET 	0x1C
#define RTC_ALRMBR_OFFSET   0x20
#define RTC_WPR_OFFSET 	    0x24
#define RTC_SSR_OFFSET 		0x28
#define RTC_SHIFTR_OFFSET   0x2C
#define RTC_TSTR_OFFSET     0x30
#define RTC_TSSSR_OFFSET 	0x38
#define RTC_CALR_OFFSET 	0x3C
#define RTC_TAFCR_OFFSET 	0x40
#define RTC_ALRMASSR_OFFSET	0x44
#define RTC_ALRMBSSR_OFFSET	0x48
#define RTC_BKP0R_OFFSET	0x50
#define RTC_BKP1R_OFFSET	0x54
#define RTC_BKP2R_OFFSET	0x58
#define RTC_BKP3R_OFFSET	0x5C
#define RTC_BKP4R_OFFSET	0x60
#define RTC_BKP5R_OFFSET	0x64
#define RTC_BKP6R_OFFSET	0x68
#define RTC_BKP7R_OFFSET	0x6C
#define RTC_BKP8R_OFFSET	0x70
#define RTC_BKP9R_OFFSET	0x74
#define RTC_BKP10R_OFFSET	0x78
#define RTC_BKP11R_OFFSET	0x7C
#define RTC_BKP12R_OFFSET	0x80
#define RTC_BKP13R_OFFSET	0x84
#define RTC_BKP14R_OFFSET	0x88
#define RTC_BKP15R_OFFSET	0x8C
#define RTC_BKP16R_OFFSET	0x90
#define RTC_BKP17R_OFFSET	0x94
#define RTC_BKP18R_OFFSET	0x98
#define RTC_BKP19R_OFFSET	0x9C

/* RTC register address definitions */
#define RTC_TR          (RTC_BASE_ADDR + RTC_TR_OFFEST)
#define RTC_DR          (RTC_BASE_ADDR + RTC_DR_OFFEST)
#define RTC_CR          (RTC_BASE_ADDR + RTC_CR_OFFSET)
#define RTC_ISR         (RTC_BASE_ADDR + RTC_ISR_OFFSET)
#define RTC_PRER        (RTC_BASE_ADDR + RTC_PRER_OFFSET)
#define RTC_WUTR        (RTC_BASE_ADDR + RTC_WUTR_OFFSET)
#define RTC_CALIBR      (RTC_BASE_ADDR + RTC_CALIBR_OFFSET)
#define RTC_ALRMAR      (RTC_BASE_ADDR + RTC_ALRMAR_OFFSET)
#define RTC_ALRMBR      (RTC_BASE_ADDR + RTC_ALRMBR_OFFSET)
#define RTC_WPR         (RTC_BASE_ADDR + RTC_WPR_OFFSET)
#define RTC_SSR         (RTC_BASE_ADDR + RTC_SSR_OFFSET)
#define RTC_SHIFTR      (RTC_BASE_ADDR + RTC_SHIFTR_OFFSET)
#define RTC_TSTR        (RTC_BASE_ADDR + RTC_TSTR_OFFSET)
#define RTC_TSSSR       (RTC_BASE_ADDR + RTC_TSSSR_OFFSET)
#define RTC_CALR        (RTC_BASE_ADDR + RTC_CALR_OFFSET)
#define RTC_TAFCR       (RTC_BASE_ADDR + RTC_TAFCR_OFFSET)
#define RTC_ALRMASSR    (RTC_BASE_ADDR + RTC_ALRMASSR_OFFSET)
#define RTC_ALRMBSSR    (RTC_BASE_ADDR + RTC_ALRMBSSR_OFFSET)
#define RTC_BKP0R       (RTC_BASE_ADDR + RTC_BKP0R_OFFSET)
#define RTC_BKP1R       (RTC_BASE_ADDR + RTC_BKP1R_OFFSET)
#define RTC_BKP2R       (RTC_BASE_ADDR + RTC_BKP2R_OFFSET)
#define RTC_BKP3R       (RTC_BASE_ADDR + RTC_BKP3R_OFFSET)
#define RTC_BKP4R       (RTC_BASE_ADDR + RTC_BKP4R_OFFSET)
#define RTC_BKP5R       (RTC_BASE_ADDR + RTC_BKP5R_OFFSET)
#define RTC_BKP6R       (RTC_BASE_ADDR + RTC_BKP6R_OFFSET)
#define RTC_BKP7R       (RTC_BASE_ADDR + RTC_BKP7R_OFFSET)
#define RTC_BKP8R       (RTC_BASE_ADDR + RTC_BKP8R_OFFSET)
#define RTC_BKP9R       (RTC_BASE_ADDR + RTC_BKP9R_OFFSET)
#define RTC_BKP10R      (RTC_BASE_ADDR + RTC_BKP10R_OFFSET)
#define RTC_BKP11R      (RTC_BASE_ADDR + RTC_BKP11R_OFFSET)
#define RTC_BKP12R      (RTC_BASE_ADDR + RTC_BKP12R_OFFSET)
#define RTC_BKP13R      (RTC_BASE_ADDR + RTC_BKP13R_OFFSET)
#define RTC_BKP14R      (RTC_BASE_ADDR + RTC_BKP14R_OFFSET)
#define RTC_BKP15R      (RTC_BASE_ADDR + RTC_BKP15R_OFFSET)
#define RTC_BKP16R      (RTC_BASE_ADDR + RTC_BKP16R_OFFSET)
#define RTC_BKP17R      (RTC_BASE_ADDR + RTC_BKP17R_OFFSET)
#define RTC_BKP18R      (RTC_BASE_ADDR + RTC_BKP18R_OFFSET)
#define RTC_BKP19R      (RTC_BASE_ADDR + RTC_BKP19R_OFFSET)

#endif // RTC_REGISTERS_H