
/*
 * syscfg.h
 *
 * Defines the SYSCFG register addresses
 */

#ifndef SYSCFG_H
#define SYSCFG_H

/* SYSCFG peripheral base address from STM32F407VG reference manual, Table 1 */
#define SYSCFG_BASE_ADDR     0x40013C00

/* SYSCFG register offsets from STM32F407VG reference manual Table 40 */
#define SYSCFG_MEMRMP_OFFEST    0x00
#define SYSCFG_PMC_OFFSET       0x04
#define SYSCFG_EXTICR1_OFFSET   0x08
#define SYSCFG_EXTICR2_OFFSET   0x0C
#define SYSCFG_EXTICR3_OFFSET   0x10
#define SYSCFG_EXTICR4_OFFSET   0x14
#define SYSCFG_CMPCR_OFFSET     0x20

/* SYSCFG register addresses */
#define SYSCFG_MEMRMP   (SYSCFG_BASE_ADDR + SYSCFG_MEMRMP_OFFEST)
#define SYSCFG_PMC      (SYSCFG_BASE_ADDR + SYSCFG_PMC_OFFSET)
#define SYSCFG_EXTICR1  (SYSCFG_BASE_ADDR + SYSCFG_EXTICR1_OFFSET)
#define SYSCFG_EXTICR2  (SYSCFG_BASE_ADDR + SYSCFG_EXTICR2_OFFSET)
#define SYSCFG_EXTICR3  (SYSCFG_BASE_ADDR + SYSCFG_EXTICR3_OFFSET)
#define SYSCFG_EXTICR4  (SYSCFG_BASE_ADDR + SYSCFG_EXTICR4_OFFSET)
#define SYSCFG_CMPCR    (SYSCFG_BASE_ADDR + SYSCFG_CMPCR_OFFSET)

#endif // SYSCFG_H
